# Generated by Django 3.0.4 on 2020-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Employee_data',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=255)),
        #     ],
        # ),
    ]
